/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.my.company.telas;

import com.mycompany.utilidades.Constantes;
import com.mycompany.utilidades.Formularios;

/**
 *
 * @author liberalino.1980
 */
public class botoesEscolhas extends javax.swing.JFrame {

    /**
     * Creates new form botoesEscolhas
     * @param titleMode
     */
    public botoesEscolhas(String titleMode) {
        initComponents();
        setResizable(false);
        jLabelTitle.setText(titleMode);
        jLabelNameAcess.setText(Constantes.LOGIN_TYPE);
        titleAndPermsConteudo();
        setLocationRelativeTo(null);
    }


    
    private void titleAndPermsConteudo(){
        if(jLabelTitle.getText() == "Conteúdos"){
            if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_CLIENTE)){
            jbtnVizualizar.setEnabled(true);
            jbtnInserir.setEnabled(false);
            jbtnEditDelete.setEnabled(false);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_VENDEDOR)){
                jbtnVizualizar.setEnabled(true);
                jbtnInserir.setEnabled(true);
                jbtnEditDelete.setEnabled(false);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_ADM)){
                jbtnVizualizar.setEnabled(true);
                jbtnInserir.setEnabled(true);
                jbtnEditDelete.setEnabled(true);
            }
        }
        else if(jLabelTitle.getText() == "Vendedores"){
            if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_CLIENTE)){
            jbtnVizualizar.setEnabled(false);
            jbtnInserir.setEnabled(false);
            jbtnEditDelete.setEnabled(false);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_VENDEDOR)){
                jbtnVizualizar.setEnabled(false);
                jbtnInserir.setEnabled(false);
                jbtnEditDelete.setEnabled(false);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_ADM)){
                jbtnVizualizar.setEnabled(true);
                jbtnInserir.setEnabled(true);
                jbtnEditDelete.setEnabled(true);
            }
        }
        else if(jLabelTitle.getText() == "Clientes"){
            if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_CLIENTE)){
            jbtnVizualizar.setEnabled(false);
            jbtnInserir.setEnabled(false);
            jbtnEditDelete.setEnabled(false);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_VENDEDOR)){
                jbtnVizualizar.setEnabled(true);
                jbtnInserir.setEnabled(true);
                jbtnEditDelete.setEnabled(true);
            }
            else if(Constantes.LOGIN_TYPE.equals(Constantes.LOGIN_ADM)){
                jbtnVizualizar.setEnabled(true);
                jbtnInserir.setEnabled(true);
                jbtnEditDelete.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnInserir = new javax.swing.JButton();
        jbtnVizualizar = new javax.swing.JButton();
        jbtnVoltar = new javax.swing.JButton();
        jbtnEditDelete = new javax.swing.JButton();
        jLabelNameAcess = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbtnInserir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnInserir.setText("Inserir");
        jbtnInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnInserirMouseClicked(evt);
            }
        });
        jbtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInserirActionPerformed(evt);
            }
        });

        jbtnVizualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnVizualizar.setText("Vizualizar");
        jbtnVizualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnVizualizarMouseClicked(evt);
            }
        });
        jbtnVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVizualizarActionPerformed(evt);
            }
        });

        jbtnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnVoltar.setText("Voltar");
        jbtnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnVoltarMouseClicked(evt);
            }
        });
        jbtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVoltarActionPerformed(evt);
            }
        });

        jbtnEditDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnEditDelete.setText("Editar ou Excluir");

        jLabelNameAcess.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNameAcess.setText("dasdsadsadsad");

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("aaaaaaaaaaaaa");

        jLabel10.setText("Acesso:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNameAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbtnEditDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnInserir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVizualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitle)
                .addGap(31, 31, 31)
                .addComponent(jbtnVizualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnEditDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jbtnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameAcess)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnInserirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Formularios.botoesEscolhas = null;
    }//GEN-LAST:event_formWindowClosed

    private void jbtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnVoltarActionPerformed

    private void jbtnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnVoltarMouseClicked
        Formularios.botoesEscolhas.dispose();
    }//GEN-LAST:event_jbtnVoltarMouseClicked

    private void jbtnInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnInserirMouseClicked
        if(Formularios.cadastroConteudo == null)
            Formularios.cadastroConteudo = new cadastroConteudo();

            Formularios.cadastroConteudo.setVisible(true);
    }//GEN-LAST:event_jbtnInserirMouseClicked

    private void jbtnVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVizualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnVizualizarActionPerformed

    private void jbtnVizualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnVizualizarMouseClicked
         if(Formularios.tabelaConteudo == null)
            Formularios.tabelaConteudo = new tabelaConteudo();

            Formularios.tabelaConteudo.setVisible(true);
    }//GEN-LAST:event_jbtnVizualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(botoesEscolhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(botoesEscolhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(botoesEscolhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(botoesEscolhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new botoesEscolhas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelNameAcess;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnEditDelete;
    private javax.swing.JButton jbtnInserir;
    private javax.swing.JButton jbtnVizualizar;
    private javax.swing.JButton jbtnVoltar;
    // End of variables declaration//GEN-END:variables
}
