/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.my.company.telas;

import com.mycompany.dao.daoConteudo;
import com.mycompany.modelo.modeloConteudo;
import com.mycompany.utilidades.Formularios;
import com.mycompany.utilidades.Temporarios;
import javax.swing.JOptionPane;

/**
 *
 * @author liberalino.1980
 */
public class cadastroConteudo extends javax.swing.JFrame {

    /**
     * Creates new form conteudoClicado
     */
    public cadastroConteudo() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jtfIdConteudo.setEditable(false);
        jtfIdConteudo.setEnabled(false);
        
            if(!verificarDadosTemporarios()){
            daoConteudo daoCont = new daoConteudo();
            
            int id = daoCont.ProximoIdConteudo();
            if(id >= 0)
                jtfIdConteudo.setText(String.valueOf(id));
                
                jbtSalvarOrAdd.setText("Adicionar");
                jbtnDelete.setVisible(false);
        }
            else{
                jbtSalvarOrAdd.setText("Alterar");
                jbtnDelete.setVisible(true);
            }
    }
    
    private Boolean verificarDadosTemporarios(){
        if(Temporarios.TempObject instanceof modeloConteudo){
            int id = ((modeloConteudo) Temporarios.TempObject).getId();
            String nome = ((modeloConteudo) Temporarios.TempObject).getNome();
            int id_categoria = ((modeloConteudo) Temporarios.TempObject).getId_categoria();
            int id_genero = ((modeloConteudo) Temporarios.TempObject).getId_genero();
            
            jtfIdConteudo.setText(String.valueOf(id));
            jtfNomeConteudo.setText(String.valueOf(nome));
            jcbCategoria.setSelectedIndex(id_categoria);
            jcbGenero.setSelectedIndex(id_genero);
            
            Temporarios.TempObject = null;
            
            return true;
        }
        else{
            return false;
        }
    }

    private void addConteudo(){
        daoConteudo daoCont = new daoConteudo();
        
        if(daoCont.inserir(Integer.parseInt(jtfIdConteudo.getText()), String.valueOf(jtfNomeConteudo.getText()), jcbCategoria.getSelectedIndex(), jcbGenero.getSelectedIndex())){
            jtfIdConteudo.setText(String.valueOf(daoCont.ProximoIdConteudo()));
            jcbCategoria.setSelectedIndex(0);
            jcbGenero.setSelectedIndex(0);
            jtfNomeConteudo.setText("");
            
            JOptionPane.showMessageDialog(null, "Conteúdo inserido com sucesso");
        }
        else{
            jtfIdConteudo.setText(String.valueOf(daoCont.ProximoIdConteudo()));
            jcbCategoria.setSelectedIndex(0);
            jcbGenero.setSelectedIndex(0);
            jtfNomeConteudo.setText("");
            JOptionPane.showMessageDialog(null, "Erro ao tentar inserir conteúdo");
        }
    }
    
    private void alterarConteudo(){
        daoConteudo daoCont = new daoConteudo();
        
        if(daoCont.inserir(Integer.parseInt(jtfIdConteudo.getText()), String.valueOf(jtfNomeConteudo.getText()), jcbCategoria.getSelectedIndex(), jcbGenero.getSelectedIndex())){
        JOptionPane.showMessageDialog(null, "Conte´ddo Alterado Com Sucesso");
        
        jtfIdConteudo.setText(String.valueOf(daoCont.ProximoIdConteudo()));
        jtfNomeConteudo.setText("");
        jcbCategoria.setSelectedIndex(0);
        jcbGenero.setSelectedIndex(0);
        }else{
            JOptionPane.showMessageDialog(null, "Não Foi possivel Alterar o Conteúdo");
        }
    }
    
      private void deletarConteudo(){
        daoConteudo daoCont = new daoConteudo();
        
        if (daoCont.excluir(Integer.parseInt(jtfIdConteudo.getText()))){
        JOptionPane.showMessageDialog(null, "Conteúdo Excluido Com Sucesso");
        }else{
            JOptionPane.showMessageDialog(null, "Não Foi possivel Excluir o Conteúdo");
        }
        
        dispose();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNomeConteudo = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jbtSalvarOrAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcbGenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfIdConteudo = new javax.swing.JTextField();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nome do conteudo");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome do conteudo");

        jtfNomeConteudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeConteudoActionPerformed(evt);
            }
        });

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Selecione uma categoria", "Canais", "Filmes", "Jogos", "Series/Novelas" }));
        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Categoria");

        jbtSalvarOrAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtSalvarOrAdd.setText("Salvar alterações");
        jbtSalvarOrAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSalvarOrAddMouseClicked(evt);
            }
        });
        jbtSalvarOrAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarOrAddActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnDelete.setText("Excluir");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Gênero");

        jcbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Selecione um gênero", "Adulto", "Ação", "Comédia", "Esporte", "Infantil", "Terror" }));
        jcbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGeneroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID");

        jtfIdConteudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfIdConteudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdConteudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNomeConteudo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtSalvarOrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jcbGenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIdConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfIdConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvarOrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarOrAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarOrAddActionPerformed

    }//GEN-LAST:event_jbtSalvarOrAddActionPerformed

    private void jtfNomeConteudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeConteudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeConteudoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        deletarConteudo();       
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jcbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGeneroActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Formularios.cadastroConteudo.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Formularios.cadastroConteudo = null;
    }//GEN-LAST:event_formWindowClosed

    private void jtfIdConteudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdConteudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdConteudoActionPerformed

    private void jbtSalvarOrAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSalvarOrAddMouseClicked
        if(jbtSalvarOrAdd.getText().equals("Adcionar")){
            addConteudo();
        }
        else{
            alterarConteudo();
        }
    }//GEN-LAST:event_jbtSalvarOrAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroConteudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroConteudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtSalvarOrAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbGenero;
    private javax.swing.JTextField jtfIdConteudo;
    private javax.swing.JTextField jtfNomeConteudo;
    // End of variables declaration//GEN-END:variables
}
