/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.my.company.telas;

import com.mycompany.utilidades.Formularios;
import javax.swing.JOptionPane;

/**
 *
 * @author liberalino.1980
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu(String mode) {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        jtfLoginPermission.setText(mode);
        permissoesMode();
    }

    private menu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void permissoesMode(){
        if(jtfLoginPermission.getText() == "CLIENTE"){
            jmenuConteudo.setEnabled(true);
            jMenuVendedor.setEnabled(false);
            jMenuCliente.setEnabled(false);
            jMenuItemConteudo.setText("Vizualizar conteúdos");
        }
        else if(jtfLoginPermission.getText() == "VENDEDOR"){
            jmenuConteudo.setEnabled(true);
            jMenuVendedor.setEnabled(false);
            jMenuCliente.setEnabled(true);
        }
        else{
            jmenuConteudo.setEnabled(true);
            jMenuVendedor.setEnabled(true);
            jMenuCliente.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfLoginPermission = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuConteudo = new javax.swing.JMenu();
        jMenuItemConteudo = new javax.swing.JMenuItem();
        jMenuVendedor = new javax.swing.JMenu();
        jMenuItemVendedor = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jtfLoginPermission.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtfLoginPermission.setText("...");

        jLabel1.setText("Acesso:");

        jMenu1.setText("Opções");
        jMenu1.setPreferredSize(new java.awt.Dimension(65, 25));

        jmenuConteudo.setText("Conteúdos");

        jMenuItemConteudo.setText("Administrar Conteúdos");
        jMenuItemConteudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemConteudoMouseClicked(evt);
            }
        });
        jMenuItemConteudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConteudoActionPerformed(evt);
            }
        });
        jmenuConteudo.add(jMenuItemConteudo);

        jMenu1.add(jmenuConteudo);

        jMenuVendedor.setText("Vendedores");

        jMenuItemVendedor.setText("Administrar vendedores");
        jMenuItemVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemVendedorMouseClicked(evt);
            }
        });
        jMenuItemVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendedorActionPerformed(evt);
            }
        });
        jMenuVendedor.add(jMenuItemVendedor);

        jMenu1.add(jMenuVendedor);

        jMenuCliente.setText("Clientes");

        jMenuItemCliente.setText("Administrar clientes");
        jMenuItemCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemClienteMouseClicked(evt);
            }
        });
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCliente);

        jMenu1.add(jMenuCliente);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Sair");
        jMenu5.setPreferredSize(new java.awt.Dimension(50, 25));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu2.setText("Encerrar sistema");
        jMenu2.setPreferredSize(new java.awt.Dimension(115, 25));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLoginPermission)
                .addContainerGap(745, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLoginPermission)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Formularios.menu = null;
    }//GEN-LAST:event_formWindowClosed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        Formularios.menu.dispose();
        
        if(Formularios.login == null)
            Formularios.login = new login();
        
        Formularios.login.setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItemConteudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemConteudoMouseClicked
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemConteudoMouseClicked

    private void jMenuItemConteudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConteudoActionPerformed
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Conteúdos","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemConteudoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItemVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemVendedorMouseClicked
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemVendedorMouseClicked

    private void jMenuItemClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemClienteMouseClicked
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemClienteMouseClicked

    private void jMenuItemVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendedorActionPerformed
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Vendedores","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemVendedorActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "CLIENTE"){
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes", "CLIENTE");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else if(Formularios.botoesEscolhas == null && jtfLoginPermission.getText() == "VENDEDOR"){
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes","VENDEDOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
        else{
            Formularios.botoesEscolhas = new botoesEscolhas("Clientes","ADMINISTRADOR");
            Formularios.botoesEscolhas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemConteudo;
    private javax.swing.JMenuItem jMenuItemVendedor;
    private javax.swing.JMenu jMenuVendedor;
    private javax.swing.JMenu jmenuConteudo;
    private javax.swing.JLabel jtfLoginPermission;
    // End of variables declaration//GEN-END:variables
}
